######################
# 로컬 Service 설정 정의
######################



##### D 설정 #####
service:
  DProp:
    D1: 233
    D2: sampleText
    D3: true
    D4: 192.168.233.1, 192.168.233.2, 192.186.233.3
    D5:
      - 192.168.233.1
      - 192.168.233.2
      - 192.168.233.3
    DGroup:
      D6: 233