######################
# 로컬 Service 설정 정의
######################



##### Zookeeper 설정 #####
service:
  zookeeperProp:
    serviceEnable: true     # Zookeeper 사용여부 (true : 사용 | false : 미사용)
    retryCnt: 3             # Zookeeper 재시도 횟수
    retryInterval: 100      # Zookeeper 재시도 간격 (ms)
    lockWaitTime: 5         # Lock 대기시간 (sec)
    serverList:             # Zookeeper 서버목록
      - 192.168.0.150:2181
      - 192.168.0.151:2181
      - 192.168.0.152:2181