######################
# 상용 Service 설정 정의
######################



##### D 설정 #####
service:
  DProp:
    D1: 244
    D2: sampleText
    D3: true
    D4: 192.168.244.1, 192.168.244.2, 192.186.244.3
    D5:
      - 192.168.244.1
      - 192.168.244.2
      - 192.168.244.3
    DGroup:
      D6: 244