#######################
# 테스트 Service 설정 정의
#######################



##### D 설정 #####
service:
  DProp:
    D1: 255
    D2: sampleText
    D3: true
    D4: 192.168.255.1, 192.168.255.2, 192.186.255.3
    D5:
      - 192.168.255.1
      - 192.168.255.2
      - 192.168.255.3
    DGroup:
      D6: 255