######################
# 공통 Service 설정 정의
######################



##### C 설정 #####
service:
  CProp:
    C1: 211
    C2: sampleText
    C3: true
    C4: 192.168.211.1, 192.168.211.2, 192.186.211.3
    C5:
      - 192.168.211.1
      - 192.168.211.2
      - 192.168.211.3
    CGroup:
      C6: 211