######################
# 개발 Service 설정 정의
######################



##### D 설정 #####
service:
  DProp:
    D1: 222
    D2: sampleText
    D3: true
    D4: 192.168.222.1, 192.168.222.2, 192.186.222.3
    D5:
      - 192.168.222.1
      - 192.168.222.2
      - 192.168.222.3
    DGroup:
      D6: 222