######################
# 개발 System 설정 정의
######################



##### B 설정 #####
system:
  BProp:
    B1: 122
    B2: sampleText
    B3: true
    B4: 192.168.122.1, 192.168.122.2, 192.168.122.3
    B5:
      - 192.168.122.1
      - 192.168.122.2
      - 192.168.122.3
    BGroup:
      B6: 122