#######################
# 테스트 System 설정 정의
#######################



##### B 설정 #####
system:
  BProp:
    B1: 155
    B2: sampleText
    B3: true
    B4: 192.168.155.1, 192.168.155.2, 192.168.155.3
    B5:
      - 192.168.155.1
      - 192.168.155.2
      - 192.168.155.3
    BGroup:
      B6: 55