######################
# 로컬 System 설정 정의
######################



##### B 설정 #####
system:
  BProp:
    B1: 133
    B2: sampleText
    B3: true
    B4: 192.168.133.1, 192.168.133.2, 192.168.133.3
    B5:
      - 192.168.133.1
      - 192.168.133.2
      - 192.168.133.3
    BGroup:
      B6: 133