######################
# 상용 System 설정 정의
######################



##### B 설정 #####
system:
  BProp:
    B1: 144
    B2: sampleText
    B3: true
    B4: 192.168.144.1, 192.168.144.2, 192.168.144.3
    B5:
      - 192.168.144.1
      - 192.168.144.2
      - 192.168.144.3
    BGroup:
      B6: 144